export const WARNING_TITLES: Record<string, string> = {
  SPOF:                      'Single Point of Failure',
  MISSING_CACHE:             'Missing Cache Layer',
  CASCADING_FAILURE:         'Cascading Failure Risk',
  NO_LOAD_BALANCER:          'No Load Balancer',
  DIRECT_CLIENT_TO_DATABASE: 'Direct Client → Database',
  NO_API_GATEWAY:                  'No API Gateway',
  NO_FIREWALL:                     'No Firewall / WAF',
  DATABASE_NO_READ_REPLICA:        'No Read Replica',
  SINGLE_QUEUE_CONSUMER:           'Single Queue Consumer',
  SYNCHRONOUS_WRITE_CRITICAL_PATH: 'Sync Write on Critical Path',
  NO_DEAD_LETTER_QUEUE:            'No Dead Letter Queue',
  NO_CDN_FOR_CLIENT:               'No CDN for Clients',
  NO_OBJECT_STORAGE_FOR_MEDIA:     'No Object Storage',
  UNBOUNDED_FANOUT:                'Unbounded Fan-out',
  NO_CACHE_FOR_SEARCH:             'No Cache for Search',
  NO_RATE_LIMITING:                'No Rate Limiting',
  NO_MONITORING:                   'No Monitoring',
  NO_LOGGING:                      'No Logging',
};
